name: Trigger Review Workflow

on:
  pull_request:
    types: [opened, edited]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2  # Usa la versione corretta di actions/checkout

      - name: Trigger Review Workflow in pr-reviewer
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/paradigma-spa/pr-reviewer/actions/workflows/generate_review.yml/dispatches \
            -d '{"ref":"main","inputs":{"pr_number":"${{ github.event.pull_request.number }}","repository":"${{ github.repository }}"}}'
